service: crunchbase-test-scrape-single-page
provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  timeout: 30
package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  lambda-time:
    handler: bin/crunchbase-test-scrape-single-page
    events:
      - http:
          path: /
          method: get